---
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: node
        tag: "12.18.1"
    inputs:
      - name: source
      - name: s3-source
      - name: version
    outputs:
      - name: builtFiles
    run:
      path: sh
      args:
        - source/ci/tasks/dockerimage.sh