---
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: hub.comcast.net/xoe-digital/terraform-jq
        tag: 'v0.12.24'
    inputs:
      - name: source
    run:
      path: sh
      args:
        - source/frame/web-tier/ci/tasks/ecrcreate.sh
