---
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: yogeek/terraform-jq
        tag: 'latest'
    inputs:
      - name: source
    run:
      path: sh
      args:
        - source/ci/tasks/fargate.sh
