aws_config_non_prod: &aws_config_non_prod
   AWS_ACCESS_KEY_ID: ((awskey))
   AWS_SECRET_ACCESS_KEY: ((awssecret))

#deploy non-prod ecr vars 
deploy_vars_default_ecr: &deploy_vars_default_ecr
   S3BUCKET: ((s3bucket-non-prod))
   WORKSPACE: ((workspace-stage))
   TF_VAR_s3bucket: ((s3bucket-non-prod))
   TF_VAR_prefix: ((prefix))
   TF_VAR_environment: ((environment-stage))
   TF_VAR_naming: ((prefix))-((environment-stage))
   TF_VAR_region: ((region-east1))
   TF_VAR_ecr_repo_name: ((prefix))-((environment-stage))
   project_path: ((project-path))

#deploy non-prod fargate vars    
deploy_vars_default_fargate: &deploy_vars_default_fargate
   S3BUCKET: ((s3bucket-non-prod))
   WORKSPACE: ((workspace-stage))
   TF_VAR_naming: ((prefix))-((environment-stage))
   TF_VAR_ecr_repo_name: ((prefix))-((environment-stage))
   TF_VAR_ecr_image_uri: ((image-uri-stage))/((prefix))-((environment-stage)):latest
   TF_VAR_vpc_id: ((vpc-id-stage))
   TF_VAR_image_uri: ((image-uri-stage))
   TF_VAR_prefix: ((prefix))
   TF_VAR_docker_image_port: ((docker-image-port))
   TF_VAR_ecs_container_port: ((ecs-container-port))
   TF_VAR_healthcheck: ((healthcheck))
   TF_VAR_https_domain_name: ((https-domain-name-non-prod))
   TF_VAR_fargate_cpu: ((fargate-cpu))
   TF_VAR_fargate_memory: ((fargate-memory))
   TF_VAR_routetable_main_cidr_igw: ((routetable-main-cidr-igw))
   TF_VAR_ecs_task_execution_role: ((ecs-task-execution-role))
   TF_VAR_ecs_task_role: ((ecs-task-role))
   TF_VAR_ecs_auto_scale_role: ((ecs-auto-scale-role))
   TF_VAR_cidr_ipv4_all: ((cidr-ipv4-all))
   TF_VAR_protocol_all: ((protocol-all))
   TF_VAR_protocol_tcp: ((protocol-tcp))
   TF_VAR_ports_all: ((ports-all))
   TF_VAR_port_https: ((port-https))
   TF_VAR_region: ((region-east1))
   TF_VAR_autoscaling_min_capacity: ((autoscaling-min-capacity-east1))
   TF_VAR_autoscaling_max_capacity: ((autoscaling-max-capacity-east1))
   TF_VAR_ecs_desired_tasks: ((ecs-desired-tasks-east1))
   TF_VAR_environment: ((environment-stage))
   TF_VAR_rt_non_prod: "1"
   project_path: ((project-path))

#deploy non-prod r53 vars    
deploy_vars_default_route53: &deploy_vars_default_route53
   S3BUCKET: ((s3bucket-non-prod))
   WORKSPACE: ((workspace-stage))
   TF_VAR_region: ((region-east1))
   TF_VAR_hosted_zone_name: "byebye.click."
   TF_VAR_rt53_alias: webtier-((environment-stage))
   TF_VAR_alb_name: ((prefix))-((environment-stage))
   project_path: ((project-path))

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource


resources:
    - name: git-repo-non-prod
      type: git
      source: ((non-prod.git))
    - name: version-number-non-prod
      type: semver
      source: ((non-prod.version.s3))
    - name: artifacts-non-prod
      type: s3
      source: ((non-prod.artifacts.s3))
    - name: webtier-docker-image-stage
      type: docker-image
      source: ((stage.docker.image))      

    - name: git-repo-prod
      type: git
      source: ((prod.git))
    - name: version-number-prod
      type: semver
      source: ((prod.version.s3))
    - name: artifacts-prod
      type: s3
      source: ((prod.artifacts.s3))
    - name: webtier-docker-image-blue-east1
      type: docker-image
      source: ((prod-blue-east1.docker.image))
    - name: webtier-docker-image-blue-west2
      type: docker-image
      source: ((prod-blue-west2.docker.image))      
    - name: webtier-docker-image-green-east1
      type: docker-image
      source: ((prod-green-east1.docker.image))
    - name: webtier-docker-image-green-west2
      type: docker-image
      source: ((prod-green-west2.docker.image))       


groups:
  - name: All
    jobs:
      - create_artifact_non_prod
      - deploy_artifact_stage
  - name: non-prod
    jobs:
      - create_artifact_non_prod
      - deploy_artifact_stage
  - name: build & upload
    jobs:
      - create_artifact_non_prod
  - name: deploy-non-prod
    jobs:
      - deploy_artifact_stage

jobs:        
    - name: create_artifact_non_prod
      plan:
        - get: git-repo-non-prod
        - get: version-number-non-prod
          params: { bump: patch }
        - put: version-number-non-prod
          params: { bump: patch, file: version-number/number }
        - task: build
          file: git-repo-non-prod/frame/web-tier/ci/tasks/build.yml
          input_mapping:
            source: git-repo-non-prod
            version: version-number-non-prod
        - put: artifacts-non-prod
          params: { file: artifacts/*.gz }

    - name: create_artifact_prod
      plan:
        - get: git-repo-prod
        - get: version-number-prod
          params: { bump: patch }
        - put: version-number-prod
          params: { bump: patch, file: version-number/number }
        - task: build
          file: git-repo-prod/frame/web-tier/ci/tasks/build.yml
          input_mapping:
            source: git-repo-prod
            version: version-number-prod
        - put: artifacts-prod
          params: { file: artifacts/*.gz }

    - name: deploy_artifact_stage
      plan:
        - get: git-repo-non-prod
          trigger: false
          passed: [create_artifact_non_prod]
        - get: version-number-non-prod
        - get: artifacts-non-prod

        - task: create-ecr-repo-stage
          file: git-repo-non-prod/frame/web-tier/ci/tasks/ecrcreate.yml
          input_mapping:
            source: git-repo-non-prod
          params:
            <<: *aws_config_non_prod
            <<: *deploy_vars_default_ecr
            
        - task: docker-files
          file: git-repo-non-prod/frame/web-tier/ci/tasks/dockerimage.yml
          input_mapping:
            source: git-repo-non-prod
            s3-source: artifacts-non-prod
            version: version-number-non-prod

        - put: webtier-docker-image-stage
          params:
            build: builtFiles/frame/web-tier
            build_args:
              BASE_PATH_ARG: ((dockerfile-env-base-path-stg))

        - task: create-fargate-resources-stage
          file: git-repo-non-prod/frame/web-tier/ci/tasks/fargate.yml
          input_mapping:
            source: git-repo-non-prod
          params:
            <<: *aws_config_non_prod
            <<: *deploy_vars_default_fargate

        - task: create-route53-resource-stage
          file: git-repo-non-prod/frame/web-tier/ci/tasks/route53-create.yml
          input_mapping:
            source: git-repo-non-prod
          params:
            <<: *aws_config_non_prod
            <<: *deploy_vars_default_route53            

